# Generated by Django 4.2.13 on 2024-06-20 07:24

from django.db import migrations


def populate_ticker_model(apps, schema_editor):
    Ticker = apps.get_model('core', 'Ticker')
    db_alias = schema_editor.connection.alias

    symbols = [
        {
            'symbol': 'AAPL', 'name': 'Apple Inc.', 'price': '143.24'
        },
        {
            'symbol': 'MSFT', 'name': 'Microsoft Corporation', 'price': '277.01'
        },
        {
            'symbol': 'GOOGL', 'name': 'Alphabet Inc.', 'price': '2,800.00'
        },
        {
            'symbol': 'AMZN', 'name': 'Amazon.com Inc.', 'price': '3,500.00'
        },
        {
            'symbol': 'TSLA', 'name': 'Tesla Inc.', 'price': '679.82'
        },
        {
            'symbol': 'FB', 'name': 'Meta Platforms Inc.', 'price': '332.00'
        },
        {
            'symbol': 'NVDA', 'name': 'NVIDIA Corporation', 'price': '200.00'
        },
        {
            'symbol': 'PYPL', 'name': 'PayPal Holdings Inc.', 'price': '300.00'
        },
        {
            'symbol': 'INTC', 'name': 'Intel Corporation', 'price': '50.00'
        },
        {
            'symbol': 'AMD', 'name': 'Advanced Micro Devices Inc.', 'price': '100.00'
        }
    ]

    tickers = [
        Ticker(symbol=symbol['symbol'], name=symbol['name'], price=float(symbol['price'].replace(',', '')))
        for symbol in symbols
    ]
    Ticker.objects.using(db_alias).bulk_create(tickers)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bulkorder'),
    ]

    operations = [
        migrations.RunPython(populate_ticker_model, None),
    ]
